/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/tecnologia': typeof TecnologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/tecnologia': typeof TecnologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/sobre': typeof SobreRoute
  '/tecnologia': typeof TecnologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clientes' | '/contacto' | '/sobre' | '/tecnologia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/contacto' | '/sobre' | '/tecnologia'
  id: '__root__' | '/' | '/clientes' | '/contacto' | '/sobre' | '/tecnologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ContactoRoute: typeof ContactoRoute
  SobreRoute: typeof SobreRoute
  TecnologiaRoute: typeof TecnologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ContactoRoute: ContactoRoute,
  SobreRoute: SobreRoute,
  TecnologiaRoute: TecnologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
